/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#d0c5b2',
        'on-surface': '#e5e2e1',
        'primary-fixed-dim': '#e6c364',
        'on-background': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'on-tertiary-fixed': '#1c1b1b',
        'on-secondary-container': '#b7b5b4',
        'on-primary': '#3d2e00',
        'surface-bright': '#3a3939',
        'on-secondary-fixed-variant': '#474746',
        'on-primary-fixed': '#241a00',
        'outline-variant': '#4d4637',
        'secondary-fixed': '#e5e2e1',
        'surface-container-lowest': '#0e0e0e',
        error: '#ffb4ab',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'surface-container-low': '#1c1b1b',
        background: '#131313',
        'on-secondary-fixed': '#1b1b1b',
        'secondary-fixed-dim': '#c8c6c5',
        'primary-container': '#c9a84c',
        'surface-container': '#201f1f',
        'surface-variant': '#353534',
        'tertiary-fixed-dim': '#c8c6c5',
        secondary: '#c8c6c5',
        'inverse-primary': '#755b00',
        'inverse-surface': '#e5e2e1',
        'primary-fixed': '#ffe08f',
        'on-primary-fixed-variant': '#584400',
        'error-container': '#93000a',
        'on-primary-container': '#503d00',
        'on-tertiary': '#313030',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed-variant': '#474646',
        outline: '#99907e',
        'surface-container-highest': '#353534',
        'surface-tint': '#e6c364',
        primary: '#e6c364',
        surface: '#131313',
        'surface-dim': '#131313',
        'secondary-container': '#474746',
        tertiary: '#c9c6c6',
        'on-tertiary-container': '#40403f',
        'on-secondary': '#313030',
        'surface-container-high': '#2a2a2a',
        'tertiary-container': '#adabab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        unit: '4px',
        'stack-lg': '80px',
        gutter: '24px',
        'stack-sm': '8px',
        margin: '64px',
        'stack-md': '24px',
      },
      fontFamily: {
        'display-xl': ['Anton', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Anton', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Anton', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '100%', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '100%', letterSpacing: '0.15em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '160%', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '120%', letterSpacing: '0.04em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '160%', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '110%', letterSpacing: '0.04em', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
